# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
name: 2021-icesat2-tracks
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow=1.2.3
  - astropy=4.3.1
  - bokeh=2.4.0
  - bottleneck=1.3.2
  - cairo=1.16.0
  - cartopy=0.20.0
  - cdsapi=0.5.1
  - curl=7.79.1
  - cython=0.29.23
  - dask=2021.9.1
  - dask-core=2021.9.1
  - emcee=3.1.1
  - ffmpeg=4.3.1
  - fiona=1.8.20
  - flask=2.0.1
  - future=0.18.2
  - geopandas=0.10.0
  - h5py=3.4.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icepyx=0.4.0
  - ipykernel=6.4.1
  - ipython=7.28.0
  - jedi=0.18.0
  - json5=0.9.5
  - jupyter=1.0.0
  - jupyterlab=3.1.18
  - lmfit=1.0.2
  - markdown=3.3.4
  - matplotlib=3.4.3
  - nbconvert=6.2.0
  - netcdf4=1.5.7
  - notebook=6.4.4
  - numpy=1.21.2
  - pandas=1.3.3
  - param=1.11.1
  - piecewise-regression=1.1.2
  - pillow=8.3.2
  - pip=21.2.4
  - pyqt=5.12.3
  - python=3.7.10
  - schwimmbad=0.3.2
  - scikit-learn=1.0
  - scipy=1.7.1
  - sliderule=1.4.6
  - werkzeug=2.0.1
  - wheel=0.37.0
  - xarray=0.19.0
  - xhistogram=0.3.0
  - pip:
      - icesat2-toolkit==1.0.0.22
      - scp==0.14.1
      - wget==3.2
      - zarr==2.10.1

